# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'note_detail.ui'
#
# Created by: PyQt5 UI code generator 5.4.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Note_Detail_Win(object):
    def setupUi(self, Note_Detail_Win):
        Note_Detail_Win.setObjectName("Note_Detail_Win")
        Note_Detail_Win.resize(476, 619)
        self.gridLayoutWidget = QtWidgets.QWidget(Note_Detail_Win)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 20, 451, 581))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(-1, -1, -1, 8)
        self.gridLayout.setObjectName("gridLayout")
        self.l_detail = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.l_detail.setObjectName("l_detail")
        self.gridLayout.addWidget(self.l_detail, 3, 1, 1, 1)
        self.l_id = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l_id.setObjectName("l_id")
        self.gridLayout.addWidget(self.l_id, 5, 0, 1, 1)
        self.l_is_valid = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l_is_valid.setObjectName("l_is_valid")
        self.gridLayout.addWidget(self.l_is_valid, 5, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(100, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bt_update = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_update.sizePolicy().hasHeightForWidth())
        self.bt_update.setSizePolicy(sizePolicy)
        self.bt_update.setObjectName("bt_update")
        self.horizontalLayout.addWidget(self.bt_update)
        self.bt_insert = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_insert.sizePolicy().hasHeightForWidth())
        self.bt_insert.setSizePolicy(sizePolicy)
        self.bt_insert.setObjectName("bt_insert")
        self.horizontalLayout.addWidget(self.bt_insert)
        self.bt_close = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_close.sizePolicy().hasHeightForWidth())
        self.bt_close.setSizePolicy(sizePolicy)
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout.addWidget(self.bt_close)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.l_date = QtWidgets.QLabel(self.gridLayoutWidget)
        self.l_date.setMaximumSize(QtCore.QSize(338, 16777215))
        self.l_date.setAlignment(QtCore.Qt.AlignCenter)
        self.l_date.setObjectName("l_date")
        self.gridLayout.addWidget(self.l_date, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.l_title = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.l_title.setObjectName("l_title")
        self.gridLayout.addWidget(self.l_title, 1, 1, 1, 1)
        self.gridLayout.setRowStretch(3, 2)
        self.gridLayout.setRowStretch(5, 1)

        self.retranslateUi(Note_Detail_Win)
        QtCore.QMetaObject.connectSlotsByName(Note_Detail_Win)

    def retranslateUi(self, Note_Detail_Win):
        _translate = QtCore.QCoreApplication.translate
        Note_Detail_Win.setWindowTitle(_translate("Note_Detail_Win", "Dialog"))
        self.l_id.setText(_translate("Note_Detail_Win", "id"))
        self.l_is_valid.setText(_translate("Note_Detail_Win", "is_valid"))
        self.bt_update.setText(_translate("Note_Detail_Win", "修改"))
        self.bt_insert.setText(_translate("Note_Detail_Win", "添加"))
        self.bt_close.setText(_translate("Note_Detail_Win", "关闭"))
        self.label.setText(_translate("Note_Detail_Win", "标题："))
        self.l_date.setText(_translate("Note_Detail_Win", "2020-12-19"))
        self.label_3.setText(_translate("Note_Detail_Win", "发布日期："))
        self.label_2.setText(_translate("Note_Detail_Win", "公告详情："))

